export const API_URL = `https://forkify-api.herokuapp.com/api/v2/recipes/`;
export const TIMEOUT_SEC = 10;
export const RESULTS_PER_PAGE = 12;
export const BUTTON_NUM = 1;
export const API_KEY =
  "bce81b64-da68-46d4-b78f-d52427bf1ce6";
export const MODAL_CLOSE_SEC = 2.5;
export const APY_KEY_SPOONACULAR =
  "bf88015445a140288c7dbc726ae58fd2";
export const APY_URL_SPOONCULAR =
  "https://api.spoonacular.com/recipes/";
export const UNIT_REC = [
  "ml ",
  "mL",
  "milliliter",
  "millilitre",
  "l",
  "L",
  "liter",
  "litre",
  "dl",
  "dL",
  "deciliter",
  "decilitre",
  "teaspoon",
  'teaspoons',
  "t",
  "tsp",
  "tablespoon",
  "tablespoons",
  "T",
  "tbl",
  "tbs",
  "tbsp",
  "fluid ounce",
  "fl oz",
  "gill",
  "cup",
  'cups',
  "c",
  "pint",
  "p",
  "pt",
  "ft pt",
  "quart",
  "q",
  "qt",
  "fl qt",
  "gallon",
  'g',
  'gal',
  'mg',
  'milligram',
  'milligramme',
  'g',
  'gram',
  'gramme',
  'kg',
  'kilogram',
  'kilogramme',
  'pound',
  'lb',
  '#',
  'ounce',
  'oz',
  'mm',
  'millimeter', 
  'millimetre',
  'cm',
  'centimeter',
  'centimetre',
  'm',
  'meter',
  'metre',
  'inch',
  'in',
  'yard',
  '°C',
  'degree celsius',
  '°F',
  'degree Farenheit'
];
